services:
  java-app:
    build:
      context: ./Core
      dockerfile: Dockerfile
    container_name: STRAIT-app
    volumes:
      - ./git_hub_authentication_file.properties:/app/git_hub_authentication_file.properties
      - ./batchConfig.json:/app/batchConfig.json
      - ./output:/app/output
      - .:/app
    depends_on:
      - derby-db
    command: ["java", "-jar", "/app.jar", "-bcf", "batchConfig.json", "-e", "-fde", "-fc", "-fdu"]
#    command: ["java", "-Xmx4g", "-XshowSettings:vm", "-jar", "/app.jar", "-bcf", "batchConfig.json", "-e", "-fde", "-fc", "-fdu"]
#    mem_limit: 5g

  derby-db:
    image: az82/docker-derby
    container_name: derby-db
    ports:
      - "1527:1527"
    volumes:
      - db_data:/derby_data
#    mem_limit: 1g

volumes:
  db_data: